version: '3.3'
services:
  mongo_project-manager:
    restart: always
    image: mongo:5.0.9
    volumes:
      - mongodb_data:/data/db
    ports:
      -  ${MONGO_PORT}:${MONGO_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=project_manager
  mongo_express_project-manager:
    restart: always
    image: mongo-express:0.54
    ports:
      - ${ME_PORT}:${ME_PORT}
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_project-manager
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=${ME_CONFIG_MONGODB_ENABLE_ADMIN}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    depends_on:
      - mongo_project-manager
  redis_project-manager:
    restart: always
    image: redis:7.0.4
    hostname: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/data
    command: redis-server --save 20 1 --loglevel warning --appendonly yes --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_REPLICATION_MODE=master
  api_project-manager:
    restart: always
    image: node:16.16.0
    volumes:
      - ~/Projects/api_project-manager:/backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - mongo_project-manager
      - redis_project-manager
    command: bash -c "mkdir -p /backend && cd /backend && yarn install && yarn dev"
  project-manager:
    restart: always
    image: node:16.16.0
    volumes:
      - ~/Projects/project-manager:/frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    command: bash -c "mkdir -p /frontend && cd /frontend && yarn install && yarn dev"
  redisInsight_project-manager:
    restart: always
    image: redislabs/redisinsight
    ports:
      - ${REDIS_INSIGHT_PORT}:${REDIS_INSIGHT_PORT}
    volumes:
      - redisInsight:/db
    depends_on:
      - redis_project-manager
volumes:
  mongodb_data:
  redis_data:
  redisInsight: